# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.redmine:
        class:   AppBundle\Controller\DefaultController
        arguments:   ['%app_redmine_user%']
        arguments:   ['%app_redmine_pass%']
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
